basePath: /
definitions:
  Server:
    properties:
      city: {type: string}
      provider: {type: string}
      public_ip: {type: string}
      state: {type: string}
      zip_code: {type: string}
    type: object
host: '[fcce:a977:eef0:ac6d:2715:0000:0000:0001]:5014'
info:
  contact: {email: fred@PageKicker.com, name: Fred Zimmerman}
  description: Sell your personal data.  Json templates from Schema.org include basic
    demographics, IAB, Myers-Briggs, and OCEAN, contact info, and best hours.
  title: Personal Data Broker
  x-21-category: utilities
  x-21-github-project-url: https://github.com/fredzannarbor/personaldatabroker
  x-21-keywords: [advertising, shopping, marketing]
  x-21-quick-buy: 21 buy pagekicker/personal-data-broker/buy/basics
  x-21-total-price: {max: 5000, min: 3000}
paths:
  /buy/basics:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: Basic demographic info about the user.
          schema:
            properties:
              server: {$ref: '#/definitions/Server'}
      summary: Returns basic demographic info about the user.
  /buy/contact:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: Contact information.
          schema:
            properties:
              server: {$ref: '#/definitions/Server'}
      summary: Returns preferred contact information.
  /buy/interests:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: User-provided list of interests.
          schema:
            properties:
              server: {$ref: '#/definitions/Server'}
      summary: Returns keywords and unstructured text describing user interests.
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest
